version: '3'

services:
  roundcubedb:
    image: mariadb:latest
    container_name: roundcube_db
    restart: always
    volumes:
        - ./mariadb:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
        - MYSQL_DATABASE=roundcubemail
    networks:
        - james-network

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 9001:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://james
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=james
    networks:
      - james-network

networks:
  james-network: